### ISSUE TITLE
Correct session fixation detection logic

### ISSUE THREAD

**Issue by fzipi** [crstest01/owasp-modsecurity-crs#485]
_Issue for tracking original pull request created by user csjperon on date 2016-08-04 20:47:28.
            Link to original PR: https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/480._

HEAD is: bb829c9cfe7e43f5d3c9abed2aa159ee2f23973f
BASE is: c168465b47fcda6d0528eb7c90c928a704f3f8cc
- Session fixation detection (rule 943110) is currently structured as follows:
  1) Check to see if a common session variable is in use for POST/GET args
  2) Check and extract the hostname from the HTTP Referer header
  3) Check to see if the Referer _starts_ with the host specified in the host header

As structured, this check could be by-passed if a malicious Referer creates a sub
domain, where the start of the domain matches the domain specified in the host header.

For example, if we have a request with the following structure:

```
-
  stage:
    input:
      headers:
        Host: somesite.com
        Referer: "https://somesite.com.attackersite.com/"
      method: GET
      port: 80
      uri: "/?phpsessid=asdfdasfadsads"
      version: HTTP/1.0
```

The request will be permitted. This change suggests that the operator is changed
to an endswith() or a @strreq (even more strict but may break Referers from sub domains).

Credits: Eric Hodel [discovered this issue]
